export const assets = {
  alert: 'alert',
  arrow: 'arrow',
  arrowbent: 'arrowbent',
  building: 'building',
  calendar: 'calendar',
  catalog: 'catalog',
  chart: 'chart',
  chevron: 'chevron',
  copy: 'copy',
  circlechevron: 'circlechevron',
  data: 'data',
  download: 'download',
  expand: 'expand',
  facebook: 'facebook',
  fax: 'fax',
  inputerror: 'inputerror',
  inputsuccess: 'inputsuccess',
  instagram: 'instagram',
  laptop: 'laptop',
  latlonglobe: 'latlonglobe',
  linkedin: 'linkedin',
  login: 'login',
  mail: 'mail',
  map: 'map',
  marker: 'marker',
  opennow: 'opennow',
  phone: 'phone',
  questionmark: 'questionmark',
  refresh: 'refresh',
  report: 'report',
  search: 'search',
  setting: 'setting',
  twitter: 'twitter',
  wheelchair: 'wheelchair',
  xlxs: 'xlxs',
  docx: 'docx',
  pdf: 'pdf',
  generic: 'generic',
  youtube: 'youtube',
  zoomin: 'zoomin',
  zoomout: 'zoomout',
  github: 'github',
  slack: 'slack',
  lock: 'lock'
};

export const svgOptions = {
  choose: '',
  ...assets
};
